# Author:           Kunal Suri, Ph.D.
# License Type:     MIT License
# Important Note:   In no circumstance shall the author(s) or copyright holder(s) be held liable for any claim, damages, or other liabilities arising from the utilization 
#                   of this code, which incorporates several code snippets generated by artificial intelligence (AI), along with opne source contributions from other programmers 
#                   sourced from GitHub and other platforms, pursuant to the terms outlined in the MIT License.
# Responsible AI:   EU's Guidelines on the responsible use of generative AI in research (European Research Area Forum) 
# URL:              https://research-and-innovation.ec.europa.eu/news/all-research-and-innovation-news/guidelines-responsible-use-generative-ai-research-developed-european-research-area-forum-2024-03-20_en
#
# Model:            bytedance/ sdxl-lightning-4step : # SDXL-Lightning by ByteDance: a fast text-to-image model that makes high-quality images in 4 steps 
# URL:              https://replicate.com/bytedance/sdxl-lightning-4step?prediction=nr53bjbbeq2sohbzopy7o66apu

import replicate

output = replicate.run(
    "bytedance/sdxl-lightning-4step:727e49a643e999d602a896c774a0658ffefea21465756a6ce24b7ea4165eba6a",
    input={
        "width": 1024,
        "height": 1024,
        "prompt": "self-portrait of a man on a ship, huge waves, lightning in the background ",
        "scheduler": "K_EULER",
        "num_outputs": 1,
        "guidance_scale": 0,
        "negative_prompt": "worst quality, low quality",
        "num_inference_steps": 4
    }
)
print(output)
